name = "HWM14"
uuid = "3e004b16-05c7-4540-98ba-c5b14e54caf7"
authors = ["Miklas Schütte <schuettem@irs.uni-stuttgart.de>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Dates = "1.11.0"
Libdl = "1.11.0"

[build]
command = "build.jl"
